version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
